export const ENDPOINTS = {
  LOGIN_EMAIL: "/auth/login-email",
  LOGIN_USERNAME: "/auth/login-username",
  REGISTER: "/auth/register",
  VERIFY_EMAIL: "/auth/verify-email",
  RESEND_VERIFICATION: "/auth/resend-verification",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  GET_PROFILE: "/auth/profile",
  GET_ALL_USERS: "/users",
  UPDATE_USER: "/user/update",
  DELETE_USER: (username) => `/users/${username}`,
  CREATE_PROJECT: "/project",
  GET_ALL_PROJECTS: "/project",
  GET_MY_PROJECTS: "/project/my",
  GET_PROJECT_BY_ID: "/project",
  GET_ALL_PAYMENTS: "/payments/all",
  GET_PROJECTS_BY_USER: "/project/user",
  UPDATE_PROJECT_STATUS: "/project",
  UPDATE_PROJECT_PRICE: "/project",
  DELETE_PROJECT: "/project",
  CREATE_PAYMENT: (projectId) => `/payment/create/${projectId}`,
  GET_PAYMENT_STATUS: (orderId) => `/payment/status/${orderId}`,
  UPLOAD_ATTACHMENT: (projectId) => `/attachment/${projectId}`,
  GET_ATTACHMENTS: (projectId) => `/attachment/${projectId}`,
};